# Generated by Django 5.0.2 on 2024-03-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klien',
            name='kode',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='kode',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
