# Generated by Django 5.0.2 on 2024-03-09 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_klien_kode_alter_vendor_kode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(max_length=225)),
                ('nilai', models.SmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opsi_created_by', to='MainApp.pengguna')),
            ],
        ),
    ]
